### ISSUE TITLE
api => 2 rollout

### ISSUE THREAD

**Issue by plicease** [PerlFFI/FFI-Platypus#346]
New features:

 - [x] pass array into pointer types #227 
 - [x] NULL is returned as `undef` instead of empty list
 - [x] consider: rework `string(length)` types, which are internally is identical to `record(length)`.  In api => 1 this means that you use `string(length)*` instead of `string(length)` which is counter intuitive.  Related: https://github.com/PerlFFI/FFI-Platypus/issues/340
 - [x] document fixed length strings #340 
 - [x] ~better warnings on wrong types: https://github.com/PerlFFI/FFI-Platypus/issues/337~

Rollout steps required:

 - [x] tests that test api 0 and api 1 should also test api 2
 - [x] All internal code in lib should use api => 2 (eat our own dogfood)
 - [x] Documentation should be updated to `use FFI::Platypus 2.00` and `api => 2`.
 - [x] During late dev run of 1.00 (1.9x), `api => 2` should be allowed without `experimental => 2` without warnings (No Prod version of 1.xx should allow this)
 - [x] Release 2.00

**Comment by plicease** [comment]
>     * [ ]  consider: rework `string(length)` types, which are internally is identical to `record(length)`.  In api => 1 this means that you use `string(length)*` instead of `string(length)` which is counter intuitive.  Related: [Document fixed length strings #340](https://github.com/PerlFFI/FFI-Platypus/issues/340)

I think `string(length)` should just be an alias for `string(length)*`.  `record(length)` should still be illegal.
